### ISSUE TITLE
1.20.2 Tracking issue

### ISSUE THREAD

**Issue by TauCubed** [mrshmllow/BetterRecipeBook#81]
Currently under development in the [dev-1_20_2](https://github.com/TauCubed/BetterRecipeBook/tree/dev-1_20_2) branch.

Current issues:
- [x] Fix `brb:textures` not rendering.
- [x] Investigate/Fix missing fields on forge.
- [x] More testing needed.
- [x] Possibly remove .kra and .ase files from final jar to reduce file size.
- [x] Sprite-ify textures
- [x] Fix brewing blit offsets
- [x] Fix page buttons showing when there is only one page when scrolling and scrolling in circles is enabled

**Comment by TauCubed** [comment]
Fixed textures not rendering. Turns out the new sprite system requires that you **do not** include the file extension in the resource location.
